### ISSUE TITLE
Does it work on iOS ?

### ISSUE THREAD

**Issue by nvcken** [joshb/CocoaOpenGL-Swift#1]
If any alternative reference would help.
Thanks

**Comment by joshb** [comment]
It currently only runs on OS X. Porting it to iOS would be interesting - I might work on that after final versions of iOS 10 and Swift 3 have been released, time permitting.

**Comment by joshb** [comment]
iOS support has been added in the latest commit. The Xcode project now contains separate targets for macOS and iOS.
